# Get all contacts.
GET https://cse341groceries.onrender.com/users


# Get contact by ID.
GET https://cse341groceries.onrender.com/users/6689e78f0b756ba4f23e8141


### create user
POST https://cse341groceries.onrender.com/users HTTP/1.1 content-type: application/json

{
    "name": "gar",
    "email": "garett.lovelessgmail.com",
    "phone": "111-222-3333"
}


# Update contact information.
PUT https://cse341groceries.onrender.com/users/6689e78f0b756ba4f23e8141 HTTP/1.1
content-type: application/json

{
    "name": "garet",
    "email": "garet.loveless@gmail.com",
    "phone": "444-555-6666"
}


# Delete a contact.
DELETE https://cse341groceries.onrender.com/users/6689e78f0b756ba4f23e8141 HTTP/1.1